/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: scripts/generate-db-exports.mjs

import type { Tables, TablesInsert, TablesUpdate } from '@/types/database.types'

export const DB_TABLES = ["ChatMessage","comment","commentReaction","commentReply","follows","friendships","notifications","post","postReaction","Profile","profileLocation","registrationcodes"] as const
export type DbTableName = (typeof DB_TABLES)[number]

export type DbRow<T extends DbTableName> = Tables<T>
export type DbInsert<T extends DbTableName> = TablesInsert<T>
export type DbUpdate<T extends DbTableName> = TablesUpdate<T>
export type DbFullItem<T extends DbTableName> = DbRow<T>
export type DbDto<T extends DbTableName> = DbRow<T>

export const toDbFullItem = <T extends DbTableName>(row: DbRow<T>): DbFullItem<T> => row
export const toDbDto = <T extends DbTableName>(row: DbRow<T>): DbDto<T> => row

// ChatMessage
export type ChatMessageRow = Tables<'ChatMessage'>
export type ChatMessageInsert = TablesInsert<'ChatMessage'>
export type ChatMessageUpdate = TablesUpdate<'ChatMessage'>
export type ChatMessage = ChatMessageRow
export type ChatMessageDto = ChatMessageRow
export const toChatMessage = (row: ChatMessageRow): ChatMessage => row
export const toChatMessageDto = (row: ChatMessageRow): ChatMessageDto => row

// comment
export type CommentRow = Tables<'comment'>
export type CommentInsert = TablesInsert<'comment'>
export type CommentUpdate = TablesUpdate<'comment'>
export type Comment = CommentRow
export type CommentDto = CommentRow
export const toComment = (row: CommentRow): Comment => row
export const toCommentDto = (row: CommentRow): CommentDto => row

// commentReaction
export type CommentReactionRow = Tables<'commentReaction'>
export type CommentReactionInsert = TablesInsert<'commentReaction'>
export type CommentReactionUpdate = TablesUpdate<'commentReaction'>
export type CommentReaction = CommentReactionRow
export type CommentReactionDto = CommentReactionRow
export const toCommentReaction = (row: CommentReactionRow): CommentReaction => row
export const toCommentReactionDto = (row: CommentReactionRow): CommentReactionDto => row

// commentReply
export type CommentReplyRow = Tables<'commentReply'>
export type CommentReplyInsert = TablesInsert<'commentReply'>
export type CommentReplyUpdate = TablesUpdate<'commentReply'>
export type CommentReply = CommentReplyRow
export type CommentReplyDto = CommentReplyRow
export const toCommentReply = (row: CommentReplyRow): CommentReply => row
export const toCommentReplyDto = (row: CommentReplyRow): CommentReplyDto => row

// follows
export type FollowsRow = Tables<'follows'>
export type FollowsInsert = TablesInsert<'follows'>
export type FollowsUpdate = TablesUpdate<'follows'>
export type Follows = FollowsRow
export type FollowsDto = FollowsRow
export const toFollows = (row: FollowsRow): Follows => row
export const toFollowsDto = (row: FollowsRow): FollowsDto => row

// friendships
export type FriendshipsRow = Tables<'friendships'>
export type FriendshipsInsert = TablesInsert<'friendships'>
export type FriendshipsUpdate = TablesUpdate<'friendships'>
export type Friendships = FriendshipsRow
export type FriendshipsDto = FriendshipsRow
export const toFriendships = (row: FriendshipsRow): Friendships => row
export const toFriendshipsDto = (row: FriendshipsRow): FriendshipsDto => row

// notifications
export type NotificationsRow = Tables<'notifications'>
export type NotificationsInsert = TablesInsert<'notifications'>
export type NotificationsUpdate = TablesUpdate<'notifications'>
export type Notifications = NotificationsRow
export type NotificationsDto = NotificationsRow
export const toNotifications = (row: NotificationsRow): Notifications => row
export const toNotificationsDto = (row: NotificationsRow): NotificationsDto => row

// post
export type PostRow = Tables<'post'>
export type PostInsert = TablesInsert<'post'>
export type PostUpdate = TablesUpdate<'post'>
export type Post = PostRow
export type PostDto = PostRow
export const toPost = (row: PostRow): Post => row
export const toPostDto = (row: PostRow): PostDto => row

// postReaction
export type PostReactionRow = Tables<'postReaction'>
export type PostReactionInsert = TablesInsert<'postReaction'>
export type PostReactionUpdate = TablesUpdate<'postReaction'>
export type PostReaction = PostReactionRow
export type PostReactionDto = PostReactionRow
export const toPostReaction = (row: PostReactionRow): PostReaction => row
export const toPostReactionDto = (row: PostReactionRow): PostReactionDto => row

// Profile
export type ProfileRow = Tables<'Profile'>
export type ProfileInsert = TablesInsert<'Profile'>
export type ProfileUpdate = TablesUpdate<'Profile'>
export type Profile = ProfileRow
export type ProfileDto = ProfileRow
export const toProfile = (row: ProfileRow): Profile => row
export const toProfileDto = (row: ProfileRow): ProfileDto => row

// profileLocation
export type ProfileLocationRow = Tables<'profileLocation'>
export type ProfileLocationInsert = TablesInsert<'profileLocation'>
export type ProfileLocationUpdate = TablesUpdate<'profileLocation'>
export type ProfileLocation = ProfileLocationRow
export type ProfileLocationDto = ProfileLocationRow
export const toProfileLocation = (row: ProfileLocationRow): ProfileLocation => row
export const toProfileLocationDto = (row: ProfileLocationRow): ProfileLocationDto => row

// registrationcodes
export type RegistrationcodesRow = Tables<'registrationcodes'>
export type RegistrationcodesInsert = TablesInsert<'registrationcodes'>
export type RegistrationcodesUpdate = TablesUpdate<'registrationcodes'>
export type Registrationcodes = RegistrationcodesRow
export type RegistrationcodesDto = RegistrationcodesRow
export const toRegistrationcodes = (row: RegistrationcodesRow): Registrationcodes => row
export const toRegistrationcodesDto = (row: RegistrationcodesRow): RegistrationcodesDto => row

