/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: scripts/generate-db-exports.mjs

import type { Enums, Tables, TablesInsert, TablesUpdate } from '@/types/database.types'

export const DB_TABLES = ["ChatMessage","comment","commentReaction","commentReply","CommentReplyReaction","friendshipRequest","friendships","notifications","post","postReaction","Profile","registrationcodes"] as const
export type DbTableName = (typeof DB_TABLES)[number]
export const DB_ENUMS = ["Lettino","notificationtype","postType","ReactionType"] as const
export type DbEnumName = (typeof DB_ENUMS)[number]

export type DbEnum<T extends DbEnumName> = Enums<T>
export type DbRow<T extends DbTableName> = Tables<T>
export type DbInsert<T extends DbTableName> = TablesInsert<T>
export type DbUpdate<T extends DbTableName> = TablesUpdate<T>
export type DbFullItem<T extends DbTableName> = DbRow<T>
export type DbDto<T extends DbTableName> = DbRow<T>

export const toDbEnum = <T extends DbEnumName>(value: DbEnum<T>): DbEnum<T> => value
export const toDbFullItem = <T extends DbTableName>(row: DbRow<T>): DbFullItem<T> => row
export const toDbDto = <T extends DbTableName>(row: DbRow<T>): DbDto<T> => row

// enum Lettino
export type Lettino = Enums<'Lettino'>
export const toLettino = (value: Lettino): Lettino => value

// enum notificationtype
export type notificationtype = Enums<'notificationtype'>
export type Notificationtype = Enums<'notificationtype'>
export const toNotificationtype = (value: Notificationtype): Notificationtype => value

// enum postType
export type postType = Enums<'postType'>
export type PostType = Enums<'postType'>
export const toPostType = (value: PostType): PostType => value

// enum ReactionType
export type ReactionType = Enums<'ReactionType'>
export const toReactionType = (value: ReactionType): ReactionType => value

// ChatMessage
export type ChatMessageRow = Tables<'ChatMessage'>
export type ChatMessageInsert = TablesInsert<'ChatMessage'>
export type ChatMessageUpdate = TablesUpdate<'ChatMessage'>
export type ChatMessage = ChatMessageRow
export type ChatMessageDto = ChatMessageRow
export const toChatMessage = (row: ChatMessageRow): ChatMessage => row
export const toChatMessageDto = (row: ChatMessageRow): ChatMessageDto => row

// comment
export type CommentRow = Tables<'comment'>
export type CommentInsert = TablesInsert<'comment'>
export type CommentUpdate = TablesUpdate<'comment'>
export type Comment = CommentRow
export type CommentDto = CommentRow
export const toComment = (row: CommentRow): Comment => row
export const toCommentDto = (row: CommentRow): CommentDto => row

// commentReaction
export type CommentReactionRow = Tables<'commentReaction'>
export type CommentReactionInsert = TablesInsert<'commentReaction'>
export type CommentReactionUpdate = TablesUpdate<'commentReaction'>
export type CommentReaction = CommentReactionRow
export type CommentReactionDto = CommentReactionRow
export const toCommentReaction = (row: CommentReactionRow): CommentReaction => row
export const toCommentReactionDto = (row: CommentReactionRow): CommentReactionDto => row

// commentReply
export type CommentReplyRow = Tables<'commentReply'>
export type CommentReplyInsert = TablesInsert<'commentReply'>
export type CommentReplyUpdate = TablesUpdate<'commentReply'>
export type CommentReply = CommentReplyRow
export type CommentReplyDto = CommentReplyRow
export const toCommentReply = (row: CommentReplyRow): CommentReply => row
export const toCommentReplyDto = (row: CommentReplyRow): CommentReplyDto => row

// CommentReplyReaction
export type CommentReplyReactionRow = Tables<'CommentReplyReaction'>
export type CommentReplyReactionInsert = TablesInsert<'CommentReplyReaction'>
export type CommentReplyReactionUpdate = TablesUpdate<'CommentReplyReaction'>
export type CommentReplyReaction = CommentReplyReactionRow
export type CommentReplyReactionDto = CommentReplyReactionRow
export const toCommentReplyReaction = (row: CommentReplyReactionRow): CommentReplyReaction => row
export const toCommentReplyReactionDto = (row: CommentReplyReactionRow): CommentReplyReactionDto => row

// friendshipRequest
export type FriendshipRequestRow = Tables<'friendshipRequest'>
export type FriendshipRequestInsert = TablesInsert<'friendshipRequest'>
export type FriendshipRequestUpdate = TablesUpdate<'friendshipRequest'>
export type FriendshipRequest = FriendshipRequestRow
export type FriendshipRequestDto = FriendshipRequestRow
export const toFriendshipRequest = (row: FriendshipRequestRow): FriendshipRequest => row
export const toFriendshipRequestDto = (row: FriendshipRequestRow): FriendshipRequestDto => row

// friendships
export type FriendshipsRow = Tables<'friendships'>
export type FriendshipsInsert = TablesInsert<'friendships'>
export type FriendshipsUpdate = TablesUpdate<'friendships'>
export type Friendships = FriendshipsRow
export type FriendshipsDto = FriendshipsRow
export const toFriendships = (row: FriendshipsRow): Friendships => row
export const toFriendshipsDto = (row: FriendshipsRow): FriendshipsDto => row

// notifications
export type NotificationsRow = Tables<'notifications'>
export type NotificationsInsert = TablesInsert<'notifications'>
export type NotificationsUpdate = TablesUpdate<'notifications'>
export type Notifications = NotificationsRow
export type NotificationsDto = NotificationsRow
export const toNotifications = (row: NotificationsRow): Notifications => row
export const toNotificationsDto = (row: NotificationsRow): NotificationsDto => row

// post
export type PostRow = Tables<'post'>
export type PostInsert = TablesInsert<'post'>
export type PostUpdate = TablesUpdate<'post'>
export type Post = PostRow
export type PostDto = PostRow
export const toPost = (row: PostRow): Post => row
export const toPostDto = (row: PostRow): PostDto => row

// postReaction
export type PostReactionRow = Tables<'postReaction'>
export type PostReactionInsert = TablesInsert<'postReaction'>
export type PostReactionUpdate = TablesUpdate<'postReaction'>
export type PostReaction = PostReactionRow
export type PostReactionDto = PostReactionRow
export const toPostReaction = (row: PostReactionRow): PostReaction => row
export const toPostReactionDto = (row: PostReactionRow): PostReactionDto => row

// Profile
export type ProfileRow = Tables<'Profile'>
export type ProfileInsert = TablesInsert<'Profile'>
export type ProfileUpdate = TablesUpdate<'Profile'>
export type Profile = ProfileRow
export type ProfileDto = ProfileRow
export const toProfile = (row: ProfileRow): Profile => row
export const toProfileDto = (row: ProfileRow): ProfileDto => row

// registrationcodes
export type RegistrationcodesRow = Tables<'registrationcodes'>
export type RegistrationcodesInsert = TablesInsert<'registrationcodes'>
export type RegistrationcodesUpdate = TablesUpdate<'registrationcodes'>
export type Registrationcodes = RegistrationcodesRow
export type RegistrationcodesDto = RegistrationcodesRow
export const toRegistrationcodes = (row: RegistrationcodesRow): Registrationcodes => row
export const toRegistrationcodesDto = (row: RegistrationcodesRow): RegistrationcodesDto => row

